// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: PendantUI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_screen1
void ui_screen1_screen_init(void);
lv_obj_t * ui_screen1;
lv_obj_t * ui_tabview1;
lv_obj_t * ui_status;
void ui_event_buttonwork(lv_event_t * e);
lv_obj_t * ui_buttonwork;
lv_obj_t * ui_label4;
void ui_event_buttonmachine(lv_event_t * e);
lv_obj_t * ui_buttonmachine;
lv_obj_t * ui_label5;
lv_obj_t * ui_panelwork;
lv_obj_t * ui_xcaption;
lv_obj_t * ui_xvalue;
lv_obj_t * ui_ycaption;
lv_obj_t * ui_yvalue;
lv_obj_t * ui_zcaption;
lv_obj_t * ui_zvalue;
lv_obj_t * ui_xzero;
lv_obj_t * ui_label3;
lv_obj_t * ui_yzero;
lv_obj_t * ui_label1;
lv_obj_t * ui_zzero;
lv_obj_t * ui_label2;
lv_obj_t * ui_panelmachine;
lv_obj_t * ui_xmachinecaption;
lv_obj_t * ui_xmachinevalue;
lv_obj_t * ui_ymachinecaption;
lv_obj_t * ui_ymachinevalue;
lv_obj_t * ui_zmachinecaption;
lv_obj_t * ui_zmachinevalue;
lv_obj_t * ui_paneloverrides;
lv_obj_t * ui_feedoverridecaption;
lv_obj_t * ui_feedoverridevalue;
lv_obj_t * ui_feedoverridepercent;
void ui_event_feedoverrideslider(lv_event_t * e);
lv_obj_t * ui_feedoverrideslider;
lv_obj_t * ui_spindleoverridecaption;
lv_obj_t * ui_spindleoverridevalue;
lv_obj_t * ui_spindleoverridepercent;
void ui_event_spindleoverrideslider(lv_event_t * e);
lv_obj_t * ui_spindleoverrideslider;
lv_obj_t * ui_rapidoverridecaption;
void ui_event_rapidoverrideslider(lv_event_t * e);
lv_obj_t * ui_rapidoverrideslider;
lv_obj_t * ui_rapidoverridevalue;
lv_obj_t * ui_rapidoverridepercent;
lv_obj_t * ui_spindlerpmpanel;
lv_obj_t * ui_spindlerpmlabel;
lv_obj_t * ui_spindlerpmvalue;
lv_obj_t * ui_feedratepanel;
lv_obj_t * ui_feedratelabel;
lv_obj_t * ui_feedratevalue;
lv_obj_t * ui_statuscontainer;
lv_obj_t * ui_coolantstatus;
lv_obj_t * ui_coolantstatuslabel;
lv_obj_t * ui_machinestatus;
lv_obj_t * ui_machinestatuslabel;
lv_obj_t * ui_xstatus;
lv_obj_t * ui_xstatuslabel;
lv_obj_t * ui_ystatus;
lv_obj_t * ui_ystatuslabel;
lv_obj_t * ui_zstatus;
lv_obj_t * ui_zstatuslabel;
lv_obj_t * ui_settings;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_buttonwork(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_panelmachine, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_panelwork, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_buttonmachine(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_panelwork, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_panelmachine, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_feedoverrideslider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_feedoverridevalue, target, "", "");
    }
}
void ui_event_spindleoverrideslider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_spindleoverridevalue, target, "", "");
    }
}
void ui_event_rapidoverrideslider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_rapidoverridevalue, target, "", "");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_screen1);
}
