// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: PendantUI

#ifndef _PENDANTUI_UI_H
#define _PENDANTUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_screen1
void ui_screen1_screen_init(void);
extern lv_obj_t * ui_screen1;
extern lv_obj_t * ui_tabview1;
extern lv_obj_t * ui_status;
void ui_event_buttonwork(lv_event_t * e);
extern lv_obj_t * ui_buttonwork;
extern lv_obj_t * ui_label4;
void ui_event_buttonmachine(lv_event_t * e);
extern lv_obj_t * ui_buttonmachine;
extern lv_obj_t * ui_label5;
extern lv_obj_t * ui_panelwork;
extern lv_obj_t * ui_xcaption;
extern lv_obj_t * ui_xvalue;
extern lv_obj_t * ui_ycaption;
extern lv_obj_t * ui_yvalue;
extern lv_obj_t * ui_zcaption;
extern lv_obj_t * ui_zvalue;
extern lv_obj_t * ui_xzero;
extern lv_obj_t * ui_label3;
extern lv_obj_t * ui_yzero;
extern lv_obj_t * ui_label1;
extern lv_obj_t * ui_zzero;
extern lv_obj_t * ui_label2;
extern lv_obj_t * ui_panelmachine;
extern lv_obj_t * ui_xmachinecaption;
extern lv_obj_t * ui_xmachinevalue;
extern lv_obj_t * ui_ymachinecaption;
extern lv_obj_t * ui_ymachinevalue;
extern lv_obj_t * ui_zmachinecaption;
extern lv_obj_t * ui_zmachinevalue;
extern lv_obj_t * ui_paneloverrides;
extern lv_obj_t * ui_feedoverridecaption;
extern lv_obj_t * ui_feedoverridevalue;
extern lv_obj_t * ui_feedoverridepercent;
void ui_event_feedoverrideslider(lv_event_t * e);
extern lv_obj_t * ui_feedoverrideslider;
extern lv_obj_t * ui_spindleoverridecaption;
extern lv_obj_t * ui_spindleoverridevalue;
extern lv_obj_t * ui_spindleoverridepercent;
void ui_event_spindleoverrideslider(lv_event_t * e);
extern lv_obj_t * ui_spindleoverrideslider;
extern lv_obj_t * ui_rapidoverridecaption;
void ui_event_rapidoverrideslider(lv_event_t * e);
extern lv_obj_t * ui_rapidoverrideslider;
extern lv_obj_t * ui_rapidoverridevalue;
extern lv_obj_t * ui_rapidoverridepercent;
extern lv_obj_t * ui_spindlerpmpanel;
extern lv_obj_t * ui_spindlerpmlabel;
extern lv_obj_t * ui_spindlerpmvalue;
extern lv_obj_t * ui_feedratepanel;
extern lv_obj_t * ui_feedratelabel;
extern lv_obj_t * ui_feedratevalue;
extern lv_obj_t * ui_statuscontainer;
extern lv_obj_t * ui_coolantstatus;
extern lv_obj_t * ui_coolantstatuslabel;
extern lv_obj_t * ui_machinestatus;
extern lv_obj_t * ui_machinestatuslabel;
extern lv_obj_t * ui_xstatus;
extern lv_obj_t * ui_xstatuslabel;
extern lv_obj_t * ui_ystatus;
extern lv_obj_t * ui_ystatuslabel;
extern lv_obj_t * ui_zstatus;
extern lv_obj_t * ui_zstatuslabel;
extern lv_obj_t * ui_settings;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
