// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: PendantUI

#include "../ui.h"

void ui_screen1_screen_init(void)
{
    ui_screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tabview1 = lv_tabview_create(ui_screen1);
    lv_tabview_set_tab_bar_position(ui_tabview1, LV_DIR_BOTTOM);
    lv_tabview_set_tab_bar_size(ui_tabview1, 50);
    lv_obj_set_width(ui_tabview1, lv_pct(100));
    lv_obj_set_height(ui_tabview1, lv_pct(100));
    lv_obj_remove_flag(ui_tabview1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_tabview1, lv_color_hex(0xF3F3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tabview1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_status = lv_tabview_add_tab(ui_tabview1, "Status");
    lv_obj_add_flag(ui_status, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW |
                    LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_remove_flag(ui_status, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_status, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_status, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonwork = lv_button_create(ui_status);
    lv_obj_set_width(ui_buttonwork, 90);
    lv_obj_set_height(ui_buttonwork, 41);
    lv_obj_set_x(ui_buttonwork, 9);
    lv_obj_set_y(ui_buttonwork, 125);
    lv_obj_add_state(ui_buttonwork, LV_STATE_USER_1);       /// States
    lv_obj_add_flag(ui_buttonwork, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonwork, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_buttonwork, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_buttonwork, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_buttonwork, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_buttonwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_buttonwork, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonwork, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_buttonwork, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_buttonwork, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_buttonwork, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_buttonwork, lv_color_hex(0x838183), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_buttonwork, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_color(ui_buttonwork, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_buttonwork, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_font(ui_buttonwork, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_USER_2);

    ui_label4 = lv_label_create(ui_buttonwork);
    lv_obj_set_width(ui_label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label4, 0);
    lv_obj_set_y(ui_label4, 3);
    lv_obj_set_align(ui_label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label4, "WORK");

    ui_buttonmachine = lv_button_create(ui_status);
    lv_obj_set_width(ui_buttonmachine, 110);
    lv_obj_set_height(ui_buttonmachine, 41);
    lv_obj_set_x(ui_buttonmachine, 109);
    lv_obj_set_y(ui_buttonmachine, 125);
    lv_obj_add_flag(ui_buttonmachine, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonmachine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonmachine, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonmachine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_buttonmachine, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_buttonmachine, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_buttonmachine, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_buttonmachine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_buttonmachine, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_buttonmachine, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_buttonmachine, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_buttonmachine, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_buttonmachine, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_buttonmachine, lv_color_hex(0x838183), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_buttonmachine, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_color(ui_buttonmachine, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_buttonmachine, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_font(ui_buttonmachine, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_USER_2);

    ui_label5 = lv_label_create(ui_buttonmachine);
    lv_obj_set_width(ui_label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label5, 0);
    lv_obj_set_y(ui_label5, 3);
    lv_obj_set_align(ui_label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label5, "MACHINE");

    ui_panelwork = lv_obj_create(ui_status);
    lv_obj_set_width(ui_panelwork, 228);
    lv_obj_set_height(ui_panelwork, 134);
    lv_obj_remove_flag(ui_panelwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_panelwork, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelwork, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_panelwork, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_panelwork, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xcaption = lv_label_create(ui_panelwork);
    lv_obj_set_width(ui_xcaption, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xcaption, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_xcaption, "X");
    lv_obj_set_style_text_color(ui_xcaption, lv_color_hex(0x3B415C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_xcaption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xcaption, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xvalue = lv_label_create(ui_panelwork);
    lv_obj_set_width(ui_xvalue, 105);
    lv_obj_set_height(ui_xvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_xvalue, 25);
    lv_obj_set_y(ui_xvalue, -3);
    lv_label_set_text(ui_xvalue, "0.0000");
    lv_obj_set_style_text_align(ui_xvalue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xvalue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ycaption = lv_label_create(ui_panelwork);
    lv_obj_set_width(ui_ycaption, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ycaption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ycaption, 0);
    lv_obj_set_y(ui_ycaption, 38);
    lv_label_set_text(ui_ycaption, "Y");
    lv_obj_set_style_text_color(ui_ycaption, lv_color_hex(0x3B415C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ycaption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ycaption, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yvalue = lv_label_create(ui_panelwork);
    lv_obj_set_width(ui_yvalue, 105);
    lv_obj_set_height(ui_yvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_yvalue, 25);
    lv_obj_set_y(ui_yvalue, 35);
    lv_label_set_text(ui_yvalue, "0.0000");
    lv_obj_set_style_text_align(ui_yvalue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_yvalue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zcaption = lv_label_create(ui_panelwork);
    lv_obj_set_width(ui_zcaption, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zcaption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zcaption, 0);
    lv_obj_set_y(ui_zcaption, 76);
    lv_label_set_text(ui_zcaption, "Z");
    lv_obj_set_style_text_color(ui_zcaption, lv_color_hex(0x3B415C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zcaption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zcaption, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zvalue = lv_label_create(ui_panelwork);
    lv_obj_set_width(ui_zvalue, 105);
    lv_obj_set_height(ui_zvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zvalue, 25);
    lv_obj_set_y(ui_zvalue, 73);
    lv_label_set_text(ui_zvalue, "0.0000");
    lv_obj_set_style_text_align(ui_zvalue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zvalue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xzero = lv_button_create(ui_panelwork);
    lv_obj_set_width(ui_xzero, 56);
    lv_obj_set_height(ui_xzero, 33);
    lv_obj_set_x(ui_xzero, 138);
    lv_obj_set_y(ui_xzero, -6);
    lv_obj_add_flag(ui_xzero, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_xzero, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_xzero, lv_color_hex(0xC50000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_xzero, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label3 = lv_label_create(ui_xzero);
    lv_obj_set_width(ui_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label3, "ZERO");

    ui_yzero = lv_button_create(ui_panelwork);
    lv_obj_set_width(ui_yzero, 56);
    lv_obj_set_height(ui_yzero, 33);
    lv_obj_set_x(ui_yzero, 138);
    lv_obj_set_y(ui_yzero, 32);
    lv_obj_add_flag(ui_yzero, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_yzero, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_yzero, lv_color_hex(0xC50000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_yzero, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label1 = lv_label_create(ui_yzero);
    lv_obj_set_width(ui_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1, "ZERO");

    ui_zzero = lv_button_create(ui_panelwork);
    lv_obj_set_width(ui_zzero, 56);
    lv_obj_set_height(ui_zzero, 33);
    lv_obj_set_x(ui_zzero, 138);
    lv_obj_set_y(ui_zzero, 70);
    lv_obj_add_flag(ui_zzero, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_zzero, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_zzero, lv_color_hex(0xC50000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zzero, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2 = lv_label_create(ui_zzero);
    lv_obj_set_width(ui_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2, "ZERO");

    ui_panelmachine = lv_obj_create(ui_status);
    lv_obj_set_width(ui_panelmachine, 228);
    lv_obj_set_height(ui_panelmachine, 134);
    lv_obj_add_flag(ui_panelmachine, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_panelmachine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_panelmachine, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelmachine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelmachine, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_panelmachine, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_panelmachine, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xmachinecaption = lv_label_create(ui_panelmachine);
    lv_obj_set_width(ui_xmachinecaption, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xmachinecaption, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_xmachinecaption, "X");
    lv_obj_set_style_text_color(ui_xmachinecaption, lv_color_hex(0x3B415C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_xmachinecaption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xmachinecaption, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xmachinevalue = lv_label_create(ui_panelmachine);
    lv_obj_set_width(ui_xmachinevalue, 105);
    lv_obj_set_height(ui_xmachinevalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_xmachinevalue, 25);
    lv_obj_set_y(ui_xmachinevalue, -3);
    lv_label_set_text(ui_xmachinevalue, "0.0000");
    lv_obj_set_style_text_align(ui_xmachinevalue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xmachinevalue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ymachinecaption = lv_label_create(ui_panelmachine);
    lv_obj_set_width(ui_ymachinecaption, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ymachinecaption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ymachinecaption, 0);
    lv_obj_set_y(ui_ymachinecaption, 38);
    lv_label_set_text(ui_ymachinecaption, "Y");
    lv_obj_set_style_text_color(ui_ymachinecaption, lv_color_hex(0x3B415C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ymachinecaption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ymachinecaption, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ymachinevalue = lv_label_create(ui_panelmachine);
    lv_obj_set_width(ui_ymachinevalue, 105);
    lv_obj_set_height(ui_ymachinevalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ymachinevalue, 25);
    lv_obj_set_y(ui_ymachinevalue, 35);
    lv_label_set_text(ui_ymachinevalue, "0.0000");
    lv_obj_set_style_text_align(ui_ymachinevalue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ymachinevalue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zmachinecaption = lv_label_create(ui_panelmachine);
    lv_obj_set_width(ui_zmachinecaption, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zmachinecaption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zmachinecaption, 0);
    lv_obj_set_y(ui_zmachinecaption, 76);
    lv_label_set_text(ui_zmachinecaption, "Z");
    lv_obj_set_style_text_color(ui_zmachinecaption, lv_color_hex(0x3B415C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zmachinecaption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zmachinecaption, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zmachinevalue = lv_label_create(ui_panelmachine);
    lv_obj_set_width(ui_zmachinevalue, 105);
    lv_obj_set_height(ui_zmachinevalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_zmachinevalue, 25);
    lv_obj_set_y(ui_zmachinevalue, 73);
    lv_label_set_text(ui_zmachinevalue, "0.0000");
    lv_obj_set_style_text_align(ui_zmachinevalue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zmachinevalue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_paneloverrides = lv_obj_create(ui_status);
    lv_obj_set_width(ui_paneloverrides, 205);
    lv_obj_set_height(ui_paneloverrides, 167);
    lv_obj_set_x(ui_paneloverrides, 243);
    lv_obj_set_y(ui_paneloverrides, 0);
    lv_obj_remove_flag(ui_paneloverrides, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_paneloverrides, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_paneloverrides, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_paneloverrides, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_paneloverrides, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_paneloverrides, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_feedoverridecaption = lv_label_create(ui_paneloverrides);
    lv_obj_set_width(ui_feedoverridecaption, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_feedoverridecaption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_feedoverridecaption, -4);
    lv_obj_set_y(ui_feedoverridecaption, -4);
    lv_label_set_text(ui_feedoverridecaption, "Feed Override");
    lv_obj_set_style_text_color(ui_feedoverridecaption, lv_color_hex(0x3B415C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_feedoverridecaption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_feedoverridecaption, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_feedoverridevalue = lv_label_create(ui_paneloverrides);
    lv_obj_set_width(ui_feedoverridevalue, 49);
    lv_obj_set_height(ui_feedoverridevalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_feedoverridevalue, 103);
    lv_obj_set_y(ui_feedoverridevalue, -7);
    lv_label_set_text(ui_feedoverridevalue, "100");
    lv_obj_set_style_text_align(ui_feedoverridevalue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_feedoverridevalue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_feedoverridepercent = lv_label_create(ui_paneloverrides);
    lv_obj_set_width(ui_feedoverridepercent, 19);
    lv_obj_set_height(ui_feedoverridepercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_feedoverridepercent, 152);
    lv_obj_set_y(ui_feedoverridepercent, -7);
    lv_label_set_text(ui_feedoverridepercent, "%");
    lv_obj_set_style_text_align(ui_feedoverridepercent, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_feedoverridepercent, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_feedoverrideslider = lv_slider_create(ui_paneloverrides);
    lv_slider_set_range(ui_feedoverrideslider, 10, 200);
    lv_slider_set_value(ui_feedoverrideslider, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_feedoverrideslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_feedoverrideslider, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_width(ui_feedoverrideslider, 170);
    lv_obj_set_height(ui_feedoverrideslider, 11);
    lv_obj_set_x(ui_feedoverrideslider, 0);
    lv_obj_set_y(ui_feedoverrideslider, 18);


    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_feedoverrideslider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_feedoverrideslider,
                                                                                                         lv_obj_get_style_pad_right(ui_feedoverrideslider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_spindleoverridecaption = lv_label_create(ui_paneloverrides);
    lv_obj_set_width(ui_spindleoverridecaption, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spindleoverridecaption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spindleoverridecaption, -4);
    lv_obj_set_y(ui_spindleoverridecaption, 46);
    lv_label_set_text(ui_spindleoverridecaption, "Spindle Override");
    lv_obj_set_style_text_color(ui_spindleoverridecaption, lv_color_hex(0x3B415C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_spindleoverridecaption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_spindleoverridecaption, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spindleoverridevalue = lv_label_create(ui_paneloverrides);
    lv_obj_set_width(ui_spindleoverridevalue, 49);
    lv_obj_set_height(ui_spindleoverridevalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spindleoverridevalue, 103);
    lv_obj_set_y(ui_spindleoverridevalue, 43);
    lv_label_set_text(ui_spindleoverridevalue, "100");
    lv_obj_set_style_text_align(ui_spindleoverridevalue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_spindleoverridevalue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spindleoverridepercent = lv_label_create(ui_paneloverrides);
    lv_obj_set_width(ui_spindleoverridepercent, 19);
    lv_obj_set_height(ui_spindleoverridepercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spindleoverridepercent, 152);
    lv_obj_set_y(ui_spindleoverridepercent, 43);
    lv_label_set_text(ui_spindleoverridepercent, "%");
    lv_obj_set_style_text_align(ui_spindleoverridepercent, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_spindleoverridepercent, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spindleoverrideslider = lv_slider_create(ui_paneloverrides);
    lv_slider_set_range(ui_spindleoverrideslider, 10, 200);
    lv_slider_set_value(ui_spindleoverrideslider, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_spindleoverrideslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_spindleoverrideslider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_spindleoverrideslider, 170);
    lv_obj_set_height(ui_spindleoverrideslider, 11);
    lv_obj_set_x(ui_spindleoverrideslider, 0);
    lv_obj_set_y(ui_spindleoverrideslider, 68);


    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_spindleoverrideslider,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_spindleoverrideslider,
                                                                                  lv_obj_get_style_pad_right(ui_spindleoverrideslider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_rapidoverridecaption = lv_label_create(ui_paneloverrides);
    lv_obj_set_width(ui_rapidoverridecaption, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rapidoverridecaption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rapidoverridecaption, -4);
    lv_obj_set_y(ui_rapidoverridecaption, 95);
    lv_label_set_text(ui_rapidoverridecaption, "Rapid Override");
    lv_obj_set_style_text_color(ui_rapidoverridecaption, lv_color_hex(0x3B415C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rapidoverridecaption, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rapidoverridecaption, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rapidoverrideslider = lv_slider_create(ui_paneloverrides);
    lv_slider_set_range(ui_rapidoverrideslider, 10, 100);
    lv_slider_set_value(ui_rapidoverrideslider, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_rapidoverrideslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_rapidoverrideslider,
                                                                                                        0, LV_ANIM_OFF);
    lv_obj_set_width(ui_rapidoverrideslider, 170);
    lv_obj_set_height(ui_rapidoverrideslider, 11);
    lv_obj_set_x(ui_rapidoverrideslider, 0);
    lv_obj_set_y(ui_rapidoverrideslider, 121);


    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_rapidoverrideslider,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_rapidoverrideslider, lv_obj_get_style_pad_right(ui_rapidoverrideslider,
                                                                                  LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_rapidoverridevalue = lv_label_create(ui_paneloverrides);
    lv_obj_set_width(ui_rapidoverridevalue, 49);
    lv_obj_set_height(ui_rapidoverridevalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rapidoverridevalue, 103);
    lv_obj_set_y(ui_rapidoverridevalue, 93);
    lv_label_set_text(ui_rapidoverridevalue, "100");
    lv_obj_set_style_text_align(ui_rapidoverridevalue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rapidoverridevalue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rapidoverridepercent = lv_label_create(ui_paneloverrides);
    lv_obj_set_width(ui_rapidoverridepercent, 19);
    lv_obj_set_height(ui_rapidoverridepercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rapidoverridepercent, 152);
    lv_obj_set_y(ui_rapidoverridepercent, 93);
    lv_label_set_text(ui_rapidoverridepercent, "%");
    lv_obj_set_style_text_align(ui_rapidoverridepercent, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rapidoverridepercent, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spindlerpmpanel = lv_obj_create(ui_status);
    lv_obj_set_width(ui_spindlerpmpanel, 107);
    lv_obj_set_height(ui_spindlerpmpanel, 60);
    lv_obj_set_x(ui_spindlerpmpanel, 0);
    lv_obj_set_y(ui_spindlerpmpanel, 180);
    lv_obj_add_state(ui_spindlerpmpanel, LV_STATE_DISABLED);       /// States
    lv_obj_remove_flag(ui_spindlerpmpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_spindlerpmpanel, lv_color_hex(0xA7A7A7), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_spindlerpmpanel, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_spindlerpmlabel = lv_label_create(ui_spindlerpmpanel);
    lv_obj_set_width(ui_spindlerpmlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spindlerpmlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spindlerpmlabel, 0);
    lv_obj_set_y(ui_spindlerpmlabel, -10);
    lv_obj_set_align(ui_spindlerpmlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spindlerpmlabel, "SPINDLE");

    ui_spindlerpmvalue = lv_label_create(ui_spindlerpmpanel);
    lv_obj_set_width(ui_spindlerpmvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spindlerpmvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spindlerpmvalue, 0);
    lv_obj_set_y(ui_spindlerpmvalue, 13);
    lv_obj_set_align(ui_spindlerpmvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spindlerpmvalue, "0 RPM");

    ui_feedratepanel = lv_obj_create(ui_status);
    lv_obj_set_width(ui_feedratepanel, 107);
    lv_obj_set_height(ui_feedratepanel, 60);
    lv_obj_set_x(ui_feedratepanel, 117);
    lv_obj_set_y(ui_feedratepanel, 180);
    lv_obj_add_state(ui_feedratepanel, LV_STATE_DISABLED);       /// States
    lv_obj_remove_flag(ui_feedratepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_feedratepanel, lv_color_hex(0xA7A7A7), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_feedratepanel, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_feedratelabel = lv_label_create(ui_feedratepanel);
    lv_obj_set_width(ui_feedratelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_feedratelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_feedratelabel, 0);
    lv_obj_set_y(ui_feedratelabel, -10);
    lv_obj_set_align(ui_feedratelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_feedratelabel, "FEED RATE");

    ui_feedratevalue = lv_label_create(ui_feedratepanel);
    lv_obj_set_width(ui_feedratevalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_feedratevalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_feedratevalue, 0);
    lv_obj_set_y(ui_feedratevalue, 13);
    lv_obj_set_align(ui_feedratevalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_feedratevalue, "0 IPM");

    ui_statuscontainer = lv_obj_create(ui_status);
    lv_obj_remove_style_all(ui_statuscontainer);
    lv_obj_set_width(ui_statuscontainer, 200);
    lv_obj_set_height(ui_statuscontainer, 58);
    lv_obj_set_x(ui_statuscontainer, 122);
    lv_obj_set_y(ui_statuscontainer, 91);
    lv_obj_set_align(ui_statuscontainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_statuscontainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_statuscontainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_statuscontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_statuscontainer, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_statuscontainer, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolantstatus = lv_obj_create(ui_statuscontainer);
    lv_obj_set_width(ui_coolantstatus, 60);
    lv_obj_set_height(ui_coolantstatus, 24);
    lv_obj_set_align(ui_coolantstatus, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_coolantstatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_coolantstatus, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_coolantstatus, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_coolantstatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_coolantstatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_coolantstatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coolantstatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_coolantstatus, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolantstatuslabel = lv_label_create(ui_coolantstatus);
    lv_obj_set_width(ui_coolantstatuslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_coolantstatuslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_coolantstatuslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_coolantstatuslabel, "Coolant");

    ui_machinestatus = lv_obj_create(ui_statuscontainer);
    lv_obj_set_width(ui_machinestatus, 60);
    lv_obj_set_height(ui_machinestatus, 24);
    lv_obj_set_align(ui_machinestatus, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_machinestatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_machinestatus, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_machinestatus, lv_color_hex(0x00B510), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_machinestatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_machinestatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_machinestatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_machinestatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_machinestatus, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_machinestatus, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_machinestatus, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_machinestatus, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_machinestatus, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_machinestatus, lv_color_hex(0xC50000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_machinestatus, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_machinestatuslabel = lv_label_create(ui_machinestatus);
    lv_obj_set_width(ui_machinestatuslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_machinestatuslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_machinestatuslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_machinestatuslabel, "Idle");

    ui_xstatus = lv_obj_create(ui_statuscontainer);
    lv_obj_set_width(ui_xstatus, 40);
    lv_obj_set_height(ui_xstatus, 24);
    lv_obj_set_align(ui_xstatus, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_xstatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_xstatus, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_xstatus, lv_color_hex(0xC50000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_xstatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_xstatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_xstatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_xstatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_xstatus, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xstatuslabel = lv_label_create(ui_xstatus);
    lv_obj_set_width(ui_xstatuslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xstatuslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_xstatuslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_xstatuslabel, "X");

    ui_ystatus = lv_obj_create(ui_statuscontainer);
    lv_obj_set_width(ui_ystatus, 40);
    lv_obj_set_height(ui_ystatus, 24);
    lv_obj_set_align(ui_ystatus, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ystatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ystatus, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ystatus, lv_color_hex(0xC50000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ystatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ystatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ystatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ystatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ystatus, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ystatuslabel = lv_label_create(ui_ystatus);
    lv_obj_set_width(ui_ystatuslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ystatuslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ystatuslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ystatuslabel, "Y");

    ui_zstatus = lv_obj_create(ui_statuscontainer);
    lv_obj_set_width(ui_zstatus, 40);
    lv_obj_set_height(ui_zstatus, 24);
    lv_obj_set_align(ui_zstatus, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_zstatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_zstatus, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_zstatus, lv_color_hex(0xC50000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zstatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_zstatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_zstatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_zstatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_zstatus, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zstatuslabel = lv_label_create(ui_zstatus);
    lv_obj_set_width(ui_zstatuslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_zstatuslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_zstatuslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_zstatuslabel, "Z");

    ui_settings = lv_tabview_add_tab(ui_tabview1, "Settings");
    lv_obj_add_flag(ui_settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW |
                    LV_OBJ_FLAG_SCROLL_ONE);     /// Flags

    lv_obj_add_event_cb(ui_buttonwork, ui_event_buttonwork, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonmachine, ui_event_buttonmachine, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_feedoverrideslider, ui_event_feedoverrideslider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_spindleoverrideslider, ui_event_spindleoverrideslider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rapidoverrideslider, ui_event_rapidoverrideslider, LV_EVENT_ALL, NULL);

}
